### ISSUE TITLE
Missing question mark in one test

### ISSUE THREAD

**Issue by rmunn** [exercism/xfsharp#135]
The Wordy test suite is missing a `?` in the "What is 4 minus -12" question. Since I had written a "is the question well-formed?" test into my solution that (among other things) tested for a question mark at the end, that meant that my code failed on that one unit test. My guess is that that difference wasn't intended, and that the "What is 4 minus -12" test should have been "What is 4 minus -12?" instead.

**Comment by ErikSchierboom** [comment]
Well spotted!

**Comment by rmunn** [comment]
I spotted it because I had written a "question ends with a ? character"
check in my solution, and the check failed on one unit test.
