### ISSUE TITLE
Additional test suggested for Parallel Letter Frequency

### ISSUE THREAD

**Issue by rmunn** [exercism/xfsharp#156]
The README for the Parallel Letter Frequency exercise is quite terse; TOO terse, in fact, because I couldn't tell if letters with diacritics (ö) were supposed to be counted along with the same letter *without* a diacritic (o). Since one of the supplied texts in the unit tests is in German, this mattered to the results. I eventually ran the three supplied texts through a letter-frequency counter. Since Python has a built-in function for that in the [`collections.Counter` class](https://docs.python.org/2.7/library/collections.html#collections.Counter) (also [available in Python 3](https://docs.python.org/3.5/library/collections.html#collections.Counter)), I used Python to check. I got the expected results when I did **not** match ö with o, so I knew how to write the code.

So that the next person who goes through this exercise won't have to go through the same verification, I suggest that the following test be added to the exercise's test suite:

```
[<Test>]
let ``Letters with and without diacritics aren't the same letter`` () =
    Assert.That(frequency ["aä"], Is.EqualTo(Map.ofList [('a', 1); ('ä', 1)]))
```

**Comment by ErikSchierboom** [comment]
@rmunn Great suggestion. I'll add the test.
