### ISSUE TITLE
Idea for new exercise

### ISSUE THREAD

**Issue by rmunn** [exercism/xfsharp#164]
There are [already](http://exercism.io/exercises/fsharp/beer-song/readme) [three](http://exercism.io/exercises/fsharp/twelve-days/readme) [exercises](http://exercism.io/exercises/fsharp/house/readme) with the basic idea of "Here is some text with a repeating pattern; write a function to print out that text". So a fourth one may not be useful. However, if a fourth such exercise *would* be useful, this Code Golf challenge could be turned into such an exercise:

http://codegolf.stackexchange.com/questions/85746/polar-bear-polar-bear-what-do-you-hear

The one thing this exercise would contain that the others wouldn't is that the "a / an" distinction in English would be relevant, and you can't easily "cheat" by baking it into the stored data. So you need a helper function to turn "Polar Bear" into "a polar bear", but "Elephant" into "an elephant".

There's a Python answer to that Code Golf challenge where the original, non-golfed version is presented, so converting that to an F# exercise should be quite quick. I could also see this as an exercise for many other languages; is there a "master" exercism repo where new exercises are suggested? Or do different language tracks just copy exercises from each other?

**Comment by ErikSchierboom** [comment]
There is indeed a repository that contains the complete list of exercises that can be implemented: https://github.com/exercism/x-common. I 

There is some discussion in the Haskell track on merging similar exercises: https://github.com/exercism/xhaskell/issues/192#issuecomment-233520256. One of the outcomes of that discussion was that the different number conversion exercises (binary, trinary, octal and hexadecimal) will be merged in a single exercise that involves converting numbers between different bases.

That discussion also mentioned the text generating exercises, which are very similar and might also be combined into a single exercise.

**Comment by ErikSchierboom** [comment]
@rmunn I'll close this issue now, as the [x-common repository](https://github.com/exercism/x-common) is the right place.
