### ISSUE TITLE
Multi-line string exercises

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/xfsharp#173]
There are quite some exercises in which the input consists of a string comprised of several lines (separated by a newline character). This virtually forces the user to always do a `Split()` call before coding the actual algorithm. We could prevent this by passing in the data as a list of lines. What do you think?

@rmunn @jwood803 @jovaneyck

**Comment by rmunn** [comment]
Agreed. Another benefit of passing in a list of lines is that it avoids having to explicitly type the parameter. The following requires explicit typing in the declaration of `f`:

```fsharp
let processOneLine s =
    printfn "%s" s
let f (s:string) =
    s.Split() |> Array.map processOneLine
```

Whereas the following does not:

```fsharp
let processOneLine s =
    printfn "%s" s
let f lines =
    lines |> List.map processOneLine
```

For the sake of type inference alone, I'd be in favor of making this change.

**Comment by jovaneyck** [comment]
+1

I'd leave in at least one exercise explicitly dealing with this just for the sake of having some string manipulation exercise. Perhaps pig-latin or wordcount?

I can count the number of times I've had to process multi-line strings in real production work on one hand :smile:

**Comment by ErikSchierboom** [comment]
I've just merged a PR that fixes this issue. As suggested, I also added a multi-line test to the `word-count` exercise.
