### ISSUE TITLE
AppVeyor build status not automatically being shown

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/xfsharp#191]
Yesterday, I looked into the issue where PR's automatically showed the Travis status but not the AppVeyor status. I logged an issue about this on the AppVeyor site:

http://help.appveyor.com/discussions/problems/5147-appveyor-build-status-does-not-automatically-show-on-github-pr

Apparently, there is some permissions problem, but as I don't own the AppVeyor account, I cannot fix it. @kytrinyx Would you be willing to check the permissions for AppVeyor, just as I did in the logged issue above?

**Comment by kytrinyx** [comment]
Oh, I bet I know what's going on. When I started my new job I had to rotate all of my github oauth tokens. Looking now.

**Comment by kytrinyx** [comment]
And now that I read that more carefully, I realize that I never did the AppVeyor integration in the first place. I think it should be working now—would you give that a try?

**Comment by ErikSchierboom** [comment]
It works!

<img width="793" alt="screen shot 2016-08-11 at 18 36 21" src="https://cloud.githubusercontent.com/assets/135246/17596620/92e4feb8-5ff2-11e6-8ec0-96dfe0820183.png">

Thanks a lot.

**Comment by ErikSchierboom** [comment]
@kytrinyx I don't know how you fixed this on AppVeyor, but it seems to not be working for the xcsharp repository. Could you check again for the xcsharp repository?

**Comment by kytrinyx** [comment]
I created an account (didn't have one) and added the xcsharp repository. I didn't do anything else. Looking now.

**Comment by kytrinyx** [comment]
Hah. No, I didn't add the xcsharp repo, I added the xfsharp repo. Adding xcsharp now.

Any other ones I should add while I'm at it?

**Comment by ErikSchierboom** [comment]
It's working! As for other repositories, I don't know. I only maintain the xcsharp and xfsharp repositories.

**Comment by kytrinyx** [comment]
Excellent. I added it for VB.NET, even though that's currently unmaintained.

**Comment by ErikSchierboom** [comment]
Good idea.
