### ISSUE TITLE
react: "Callbacks should only be called once even if multiple dependencies have changed" test has expectation on wrong cell

### ISSUE THREAD

**Issue by petertseng** [exercism/xfsharp#205]
After thinking on https://github.com/exercism/xfsharp/pull/187#discussion_r77273853, I think that `c1` should be a `c4`; it's the only cell with multiple dependencies, and `c4` would match the go implementation.

so then you ask, why don't I just fix it myself!

The reason is I think the example solution would not pass that test, and I don't know enough to fix the example solution. So, sorry, I can only file the issue.

**Comment by ErikSchierboom** [comment]
Thanks for reporting the issue. I'll look at it soon

**Comment by ErikSchierboom** [comment]
@petertseng I can confirm that you have indeed found a bug, it should be `c4` instead of `c1` in the test you mentioned. I'll work at fixing the example solution.

**Comment by ErikSchierboom** [comment]
Fixed with this [PR](https://github.com/exercism/xfsharp/pull/213).
