### ISSUE TITLE
Tests for transpose exercise need updating

### ISSUE THREAD

**Issue by rmunn** [exercism/xfsharp#217]
In https://github.com/exercism/x-common/commit/778a54887ef8bdf582a6eb0adf0bf8ddb6c73dd5, the transpose test was updated to remove two trailing spaces in the final line of the expected output, so that the test would conform to what the README says (pad to the left with spaces, but don't pad to the right). But the test for F# still has the two extra, erroneous trailing spaces.

There are also a few other tests that have been added, like the "two characters in a column" test. Refreshing the F# transpose exercise from x-common would pick those up too.

**Comment by ErikSchierboom** [comment]
Good find. We'll indeed need to update the exercise.

**Comment by ErikSchierboom** [comment]
@rmunn Fixed with this [PR](https://github.com/exercism/xfsharp/pull/219). Thanks for reporting!

p.s. I spent way too much time getting the example implementation ready. Silly me.
