### ISSUE TITLE
Linked list exercise naming

### ISSUE THREAD

**Issue by robkeim** [exercism/xfsharp#221]
Is there a reason that the Linked list exercise module is named Deque and the test file DequeTest? I'm wondering if the name of the exercise was changed at some point because roughly have of the languages that implemented this problem use the name Deque and the other half with Linked list.

**Comment by ErikSchierboom** [comment]
No good reason I think. Probably only named that way due to another track using the same name. Feel free to send a PR to correct this, although you may have to verify none of the other exercises using linked lists use the same name.

**Comment by robkeim** [comment]
Alright I think we should be good to go then as the only other exercises referencing lists are:
- `Simple Linked List`
- `List Ops`
- `Sub List`

Related [PR request](https://github.com/exercism/xfsharp/pull/222)

**Comment by ErikSchierboom** [comment]
Merged! Thanks. :tada:
