### ISSUE TITLE
Can NUnit tests be run with vscode?

### ISSUE THREAD

**Issue by hsavit1** [exercism/xfsharp#226]
On OSX - can I run the NUnit tests w/o Xamarin?  Would the ionide plugin for VSCode be enough?

**Comment by ErikSchierboom** [comment]
At this moment, no, as VSCode doesn't support test runners as far as I know. The Ionide plugin does support running FAKE scripts, which can also be used to run tests. Once [this feature](https://github.com/exercism/cli/issues/88) is implemented in the CLI, we will be working on shipping a FAKE script alongside each exercise to run the tests.

**Comment by hsavit1** [comment]
@ErikSchierboom - Thanks for getting back to me

Are there any recommended docs for running these FAKE scripts? And if there are, perhaps they should be added to the "Running the tests" section for F#. 

My laptop has very little space and I'd rather not download Xamarin if i don't have to!

**Comment by ErikSchierboom** [comment]
@hsavit1 As of today, no there are not. Once the abovementioned feature has been implemented, I'll add the FAKE scripts and update the documentation. However, this repository does use FAKE to build and test the files. For example. check out [build.fsx](https://github.com/exercism/xfsharp/blob/master/build.fsx).

**Comment by ErikSchierboom** [comment]
By the way, the FAKE documentation is also quite nice. You could try to follow their [getting started tutorial](http://fsharp.github.io/FAKE/gettingstarted.html).

**Comment by ErikSchierboom** [comment]
I'll close this issue, as it is really as VS Code feature (which I would love to see!). Hopefully, we can make things simpler in the future.
