### ISSUE TITLE
Sum of Multiples - Add an intermediary test case

### ISSUE THREAD

**Issue by mattcbaker** [exercism/xfsharp#230]
While doing the `Sum of Multiples` exercise, I ended up adding one more test case in order to solve the problem incrementally. That test case is below, what do you think about adding it to the test cases file for this problem?

```
[<Test>]
[<Ignore("Remove to run test")>]
let ``Sum to 4`` () =
    Assert.That(sumOfMultiples [3; 5] 4, Is.EqualTo(3))
```

**Comment by ErikSchierboom** [comment]
Great idea. Actually, it turns out that the updated [canonical data file](https://github.com/exercism/x-common/blob/master/exercises/sum-of-multiples/canonical-data.json) for this exercise also includes it.

**Comment by ErikSchierboom** [comment]
@mattcbaker If you're interested, you can also do this yourself! The tests of the `sum-of-multiples` exercises can be found at [exercises/sum-of-multiples/SumOfMultiplesTest.fs](https://github.com/exercism/xfsharp/blob/master/exercises/sum-of-multiples/SumOfMultiplesTest.fs). That file should contains tests for each entry in the [canonical data](https://github.com/exercism/x-common/blob/master/exercises/sum-of-multiples/canonical-data.json) file.

**Comment by mattcbaker** [comment]
@ErikSchierboom I pulled and attempted to push a PR, but I was not able to. Do I need any sort of access, or should I just try again?

**Comment by mattcbaker** [comment]
PR created https://github.com/exercism/xfsharp/pull/231

**Comment by ErikSchierboom** [comment]
The PR looks fine. It has just been merged! Thanks a lot.
