### ISSUE TITLE
Add hints to some exercises

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/xfsharp#234]
@abo64 added [this issue](https://github.com/exercism/xscala/issues/220) to the Scala track, which I thought was a brilliant plan. I'm just gonna literally copy-and-paste that issue's text:

>Most exercises have their own favorable solutions and characteristic pitfalls.
To give people some guidance and avoid writing repetitive or similar code comments again and again
we should add a HINTS.md file to any exercise where it makes sense.

>Especially the first couple of exercises should have such a file to assist beginners.
Another case is exercises dealing with special features of the language like `option` or `async`.

We should make a list of exercises for which some hints can be added. Of course, the first exercises should be more hint-heavy than the latter, although even for advanced exercises hints can be very useful. One example of this are the text parsing exercises, where we could guide people to using FParsec.

**Comment by ErikSchierboom** [comment]
The following exercises could probably use some hints:

- [ ] `helloworld`: give hints on [pattern matching](https://fsharpforfunandprofit.com/posts/match-expression/) and [sprintf](https://fsharpforfunandprofit.com/posts/printf/)
- [ ] `difference-of-squares` give hint on `Seq.sumBy`
- [ ] `sum-of-multiples`: give hint on using ranges
- [ ] `space-age`: give hint that code duplication should be avoided and that `match` expressions are favored over dictionaries
- [ ] `accumulate`: give hints about making a [tail-call recursive function](https://blogs.msdn.microsoft.com/fsharpteam/2011/07/08/tail-calls-in-f/)
- [ ] `grains`: give hint on `BigInt`
- [ ] `wordy`: give hint on using [FParsec](http://www.quanttec.com/fparsec/users-guide/)
- [ ] `diamond`: give hint on [property-based testing](https://fsharpforfunandprofit.com/posts/property-based-testing/)

TODO: the rest

**Comment by robkeim** [comment]
Great idea @abo64 and thanks @ErikSchierboom for bringing this to the F# track as well. I've gone ahead and sent a first exercise [here](https://github.com/exercism/xfsharp/pull/241) and if it looks good I'll try to take care of some of the others as well.

**Comment by ErikSchierboom** [comment]
@robkeim I've updated the list with more suggested hints.

**Comment by robkeim** [comment]
Thanks @ErikSchierboom you're making fixing this too easy by going as far as to include links :) I sent a PR with a few additional ones, and I'll try to get some more done soon.

**Comment by ErikSchierboom** [comment]
Fantastic!

**Comment by robkeim** [comment]
I added hints for the rest of the ones where I understood what you were thinking @ErikSchierboom. Here are the remaining ones (they're also unchecked above):
- Alphametics -> I haven't done this one yet myself
- Beer song -> I couldn't come up with anything that didn't seem so obvious it was patronizing :)
- Grade school -> I didn't use a map to solve this one personally, so didn't know what to say relating to the map
- Sum of multiples -> Not exactly sure what you meant by "ranges" here
- Wordy -> I haven't done this one yet myself either

I think we've got a great start here, and people can add/adopt/modify as we go along. Given that I solved these exercises a while ago, the potential pain points/traps aren't fresh in my head like when I first solved them.

**Comment by ErikSchierboom** [comment]
Fantastic! I'll do the remaining hints later this week. I just have to finish the last 10 problems of the EcmaScript track first :)

Once again, thanks for the great work!

**Comment by robkeim** [comment]
You're welcome, thanks for putting together the list.

Looking forward to being able to use your hints for the two problems I haven't solved on your list if I get stuck ;)

**Comment by ErikSchierboom** [comment]
One them must be `alphametics`. That one I struggle quite a bit with, so good luck :)

**Comment by robkeim** [comment]
Haha thanks :)

**Comment by ErikSchierboom** [comment]
All hints have been added. This issue can be closed. If we do think of more hints, we can just add them individually.

**Comment by robkeim** [comment]
Great, thanks for driving this effort @ErikSchierboom!
