### ISSUE TITLE
Make leap the second exercise

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/xfsharp#242]
At the moment, `bob` is the second exercise and `leap` is the third. My proposal is to switch the order of these two exercises, as `leap` is much easier to solve and doesn't actually introduce anything new except for the modulo operator.

**Comment by robkeim** [comment]
That sounds good to me @ErikSchierboom although I've always been surprised there isn't more cross track consistency for exercise order. I've gone ahead and sent a PR.

**Comment by ErikSchierboom** [comment]
Great!
