### ISSUE TITLE
Tree Building exercise in F# has nonsense readme

### ISSUE THREAD

**Issue by cowlike** [exercism/xfsharp#250]
From the readme:

> The ID number is always
between 0 (inclusive) and the length of the record list (exclusive). No record
has a parent ID lower than its own ID and no record, except the root record,
has a parent ID that's equal to its own ID.

These sentences are both false and violated in the tests. Maybe the design changed and someone forgot to update the readme? Currently the root node has a parent id of -1.

The root node, and at least one child of the root, must have "a parent ID lower than its own ID".

**Comment by ErikSchierboom** [comment]
Would you be interested in creating a PR to fix this?

**Comment by robkeim** [comment]
@ErikSchierboom for clarification is the issue:

1. The F# implementation is not compliant with the spec
2. The spec is not correct in x-common here:
https://github.com/exercism/x-common/blob/9a0cc1b96f2f9c8f7614f1337d8f58bd05a939b9/exercises/tree-building/description.md

**Comment by cowlike** [comment]
I can do that later today.

On Dec 16, 2016 7:22 AM, "Erik Schierboom" <notifications@github.com> wrote:

Would you be interested in creating a PR to fix this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/exercism/xfsharp/issues/250#issuecomment-267592874>,
or mute
the thread

**Comment by ErikSchierboom** [comment]
@robkeim It's number 1: the F# implementation is not correct.

@cowlike Perfect! For this exercise, you actually have to edit two files:

1. [Example.fs](https://github.com/exercism/xfsharp/blob/master/exercises/tree-building/Example.fs): the default "good" implementation.
2. [TreeBuilding.fs](https://github.com/exercism/xfsharp/blob/master/exercises/tree-building/TreeBuilding.fs): the starting "bad" point.

**Comment by cowlike** [comment]
Wait what?! The spec makes no sense to me unless the root node has the
highest ID, which is just bizarre. IMO, the root should be have ID 0 and
build up from there, meaning the parent ID is always lower.

Doing it the other way is confusing. It would make more sense to just fix
the spec to match the supposedly working version.

On Dec 16, 2016 8:22 AM, "Erik Schierboom" <notifications@github.com> wrote:

@robkeim <https://github.com/robkeim> It's number 1: the F# implementation
is not correct.

@cowlike <https://github.com/cowlike> Perfect! For this exercise, you
actually have to edit two files:

   1. Example.fs
   <https://github.com/exercism/xfsharp/blob/master/exercises/tree-building/Example.fs>:
   the default "good" implementation.
   2. TreeBuilding.fs
   <https://github.com/exercism/xfsharp/blob/master/exercises/tree-building/TreeBuilding.fs>:
   the starting "bad" point.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/exercism/xfsharp/issues/250#issuecomment-267603960>,
or mute
the thread

**Comment by robkeim** [comment]
@cowlike - The way that I read the spec is the way that you described it here:

> IMO, the root should be have ID 0 and
build up from there, meaning the parent ID is always lower.

Maybe the fact that there is a negative in the spec makes it confusing to understand?

> No record has a parent ID lower than its own ID

This implies that "all records have an ID larger than their parents"

It doesn't call out explicitly that the root node has to be zero it can be implied from the first part:

> The ID number is always between 0 (inclusive) and the length of the record list (exclusive).

**Comment by robkeim** [comment]
@cowlike Is this more clear? This is what I understood from reading the above spec

- The ID number is always between 0 (inclusive) and the length of the record list (exclusive)
- The root ID has the value 0 and is the only record to have a parent ID equal to its own ID
- All other records have a parent ID lower than their own ID

**Comment by cowlike** [comment]
No record has a parent ID lower than its own ID

This implies that "all records have an ID larger than their parents"

=========

I think you need to recheck your logic. This is the nonsense part. It
actually implies that every parent ID is >= the record ID.


On Dec 16, 2016 9:00 AM, "Rob Keim" <notifications@github.com> wrote:

@cowlike <https://github.com/cowlike> - The way that I read the spec is the
way that you described it here:

IMO, the root should be have ID 0 and
build up from there, meaning the parent ID is always lower.

Maybe the fact that there is a negative in the spec makes it confusing to
understand?

No record has a parent ID lower than its own ID

This implies that "all records have an ID larger than their parents"

It doesn't call out explicitly that the root node has to be zero it can be
implied from the first part:

The ID number is always between 0 (inclusive) and the length of the record
list (exclusive).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/exercism/xfsharp/issues/250#issuecomment-267612395>,
or mute
the thread

**Comment by cowlike** [comment]
This formulation is fine except that allowing the -1 to stay for the root
parent means you only need to fix the broken spec, which had other errors
as well (see last email)

**Comment by ErikSchierboom** [comment]
@cowlike I've create a [PR](https://github.com/exercism/x-common/pull/472) to reword the exercise's description and added a sample tree. The exercise explicitly says that the root node's parent is equal to its own ID, which is of course there to make the refactoring slightly more difficult. We should thus modify our tests and example implementations.

**Comment by robkeim** [comment]
Thanks @ErikSchierboom I just left one small comment on the PR, but other than that it's definitely much more explicit with the sample!

**Comment by cowlike** [comment]
Thanks @ErikSchierboom. At first I thought this was just a matter of clearing up the readme, since the existing code and tests works as is. However, it has turned into a far bigger problem of rewriting everything about it: readme, tests, implementation, example. 

The rewrite of the numbering part is now logically coherent. The readme also said the existing code is working (and it is, by definition since it passes the test) and your job is to refactor it. The very meaning of refactoring is to change the structure of the code such that the existing behavior is maintained, verified by ensuring you don't break the tests. 

May I ask why you chose to rewrite all the code instead of just fixing the readme to match the existing code? Starting the root with a negative parent ID is an equally valid way to construct the tree. Is this really intended to be a refactoring or a total rewrite of the "overall poor first attempt"? I'm sorry but I have to pass on any sort of PR because it's not clear what the goal is here.

**Comment by cowlike** [comment]
One more point: if this exercise is more intended to be something like "_this code is horrible, the design sucks and the poorly designed tests measure concrete implementation details instead of the desired abstract properties, so rewrite it from scratch_" then it should probably say that more clearly as well.

**Comment by ErikSchierboom** [comment]
The main reason why I chose a rewrite is to not force the other language track implementing this exercise (Go) to also change their implementations. As I see, it was just an error on my part where I did not correctly implement the exercise. Changing the readme to fix our implementation and thereby breaking some else's seemed to me the wrong way to go.

Also, I think the current requirement is a little more challenging. If the root node had a parent ID of -1, the implementation would be simpler. Now people have to consider the exception.

You can of course do a complete rewrite, but you could also try to refactor bit by bit. That's entirely up to the person doing the exercise, so I wouldn't want to force people any way.

**Comment by cowlike** [comment]
Ok, I see now. Perhaps the exercise should be pulled from the FSharp section until it is fixed. As it is now, it is completely wrong since the tests don't match the spec and therefore this is not a refactoring, by definition. So what you're asking for is new tests against the corrected spec, a good implementation of the code, and some horrible (but correct) implementation amenable to refactoring. Is that right?

**Comment by ErikSchierboom** [comment]
That is indeed what I'm suggesting. I can try to fix this within the next couple of days.

**Comment by cowlike** [comment]
I think the tests should verify the properties of the abstraction and not the implementation details such as the children of a branch being in a list. Perhaps export three functions:

1.  isBranch : 'a Tree -> bool
2. isLeaf : 'a Tree -> bool
3. children : 'a Tree -> 'a Tree list

Then testing the length of the children list or something. I'm thinking of something like this (which I believe I'll write):
```
type Tree<'a> = Leaf of 'a | Branch of 'a * 'a Tree list
let children (Branch (_, ch)) = ch //unsafe
//write some code
Branch ((0,0), []) |> children  //= 0
Branch 
    ((0,0),
        [
            Branch ((1,0), [Leaf (2,1); Leaf (4,1)]);
            Branch ((3,0), [Leaf (6,3)]);
            Branch ((5,0), [])
        ])
    |> children |> List.length  // = 3
```

**Comment by ErikSchierboom** [comment]
@cowlike That sounds like a good idea. We should probably better map the properties to tests and not test the implementation. For now, I've created a [PR](#252) to fix the current issue, so at least the exercise is in sync with the problem description.

**Comment by cowlike** [comment]
It's not at all what was requested but I wrote a [solution that implements rose trees](http://exercism.io/submissions/d7239280bb0b430296894d602cd5e1f2), or at least that was my intention! I decided to use Option rather than exceptions as well and I think they are under-utilized from what I'm seeing so far. I have no idea if this is what you were thinking or not but I wanted to have some fun with it. Maybe it can be of some use while you're changing things around.

**Comment by ErikSchierboom** [comment]
Thanks for posting it! I'll definitely have a look at it. I really like your suggestion to define the tests such that the user is free to implement the tree however he/she wants.

**Comment by ErikSchierboom** [comment]
@cowlike With #280 merged, we now have an implementation-agnostic test.

**Comment by cowlike** [comment]
That's really nice work, Erik!
