### ISSUE TITLE
Why is flatten-array forgone in this track?

### ISSUE THREAD

**Issue by masters3d** [exercism/xfsharp#265]
reference:
https://github.com/exercism/xswift/pull/228

**Comment by ErikSchierboom** [comment]
The reason for this is simple: the type system was working against me. I cannot create a list with different levels of nesting. Perhaps I could do it with a sequence, but I'd have to check.

**Comment by theprash** [comment]
The exercise described in the readme does not make sense for a statically typed language, hence the discussion around including it in the Swift track. I think it should not be included for F#.

In F# you would do the equivalent with a tree data structure where each node has a list of child nodes, but that would definitely be a different exercise with a different readme.

**Comment by ErikSchierboom** [comment]
@robkeim What do think?

**Comment by robkeim** [comment]
@ErikSchierboom what did you try in terms of creating a list with multiple levels of nesting? If we want to have a multi-level list could we do something like this:
```
type 'a ll =
    | I of 'a             // leaf Item
    | L of 'a ll list     // ' <- confine the syntax colouring confusion
 
let rec flatten = function
    | [] -> []
    | (I x)::y -> x :: (flatten y)
    | (L x)::y -> List.append (flatten x) (flatten y)
```
I got this code from [here](https://rosettacode.org/wiki/Flatten_a_list#F.23) where the same exercise is implemented in many different languages.

**Comment by masters3d** [comment]
Thank you. Got the answer I needed. :)

**Comment by ErikSchierboom** [comment]
Great! 

@robkeim I think to implement the solution as you mentioned would not really give us anything, as you already have to do flattening as part of one of the tree exercises. To me this, this exercise is more about dealing with the built-in collections and flattening them, which does not make sense in F#.

**Comment by robkeim** [comment]
That makes sense to me @ErikSchierboom.
