### ISSUE TITLE
One of the test in terms of ordering tests in KinderGarden exercise is wrong

### ISSUE THREAD

**Issue by bugra** [exercism/xfsharp#272]
I believe in KinderGarden exercise, one of the tests order is wrong, I attach the patch file for fixing this test as I do not have permission to create PR. 

Bugra

[0001-Fix-the-order-of-kindergarden-test.txt](https://github.com/exercism/xfsharp/files/679129/0001-Fix-the-order-of-kindergarden-test.txt)

**Comment by robkeim** [comment]
@bugra thanks for taking the time to open an issue! In terms of being able to create a PR, can you explain what you mean when you say you "do not have permission"? Everyone should be able to create PRs, the only access that is restricted is who can merge them.

In this particular exercise I believe the order that is given is correct based on the [readme](http://exercism.io/exercises/fsharp/kindergarten-garden/readme) which says:

> The children are assigned to cups in alphabetical order.

Taking that into account, does that explain the expected result in the test?

**Comment by bugra** [comment]
@robkeim Thanks for the explanation, I did not see the alphabetical order piece in the `README.md`.

**Comment by robkeim** [comment]
Sounds good!
