### ISSUE TITLE
Binary Search Tree - value should return an option

### ISSUE THREAD

**Issue by balazsbotond** [exercism/xfsharp#276]
[Discussion on Exercism](http://exercism.io/submissions/6e65f3cec5144a9b98180492c11c4e60)

I think it would be nicer if `value` returned an `option` because the empty node has no value. The unit tests currently don't allow this.

**Comment by ErikSchierboom** [comment]
@balazsbotond With #278 merged, this issue has been resolved. Thanks for reporting it!
