### ISSUE TITLE
Linked List: how to handle the empty list in pop and shift?

### ISSUE THREAD

**Issue by balazsbotond** [exercism/xfsharp#286]
There is currently no unit test checking what `pop` and `shift` do when the list is empty. I wonder if returning an `option` would be a better way to handle this case instead of returning the value if present or throwing an exception. Though `Map` has separate `find` and `tryFind` methods so I'm not sure if this is idiomatic.

I think adding tests for the empty case would be a good idea in any case and if you agree, I can write them. And if you think `option` is the way to go, I will change that too.

**Comment by ErikSchierboom** [comment]
I agree that testing the empty case would be a good idea. Returning an option value is also more idiomatic, so it would be great if you could also change that to

**Comment by balazsbotond** [comment]
Cool, thanks! I'll send those changes later today.

**Comment by robkeim** [comment]
Sorry I read the PR before seeing there was a related issue that I should have commented on...

Copying my comment here:

I agree this is more idiomatic, but from the [description.md](https://github.com/exercism/x-common/blob/master/exercises/linked-list/description.md) it says:

>To keep your implementation simple, the tests will not cover error conditions. Specifically: pop or shift will never be called on an empty list.
Shouldn't we stay aligned with what's in x-common?

**Comment by balazsbotond** [comment]
Sorry, I haven't read the README carefully enough. I agree with @robkeim, I think my pull request should be reverted.

**Comment by ErikSchierboom** [comment]
Whoops. Totally missed that. A retraction is then indeed better
