### ISSUE TITLE
Grep exercise test suite does not enforce correct interaction between flag combinations

### ISSUE THREAD

**Issue by nicholaslawton** [exercism/xfsharp#310]
[The test suite for the Grep exercise](http://exercism.io/exercises/fsharp/grep/test-suite) does not enforce correct behaviour for interaction between all combinations of flags.

The `One file, one match, multiple flags` and `Multiple files, one match, multiple flags` test cases do require case insensitive matching to combine with printing line numbers. And while they both also specify entire line matching, the patterns are specific entire line matches, so it doesn't matter.

It is therefore not necessary to respect all combinations of flags in order to satisfy the test suite. For example, a solution which ignores the entire line matching flag when the case insensitive flag is set will satisfy the test suite. Likewise, a solution which ignores match inversion when the case insensitive flag is set, and one which ignores entire line matching when the match inversion flag is set. There may be other combinations which are not correctly enforced as well.

**Comment by ErikSchierboom** [comment]
@nicholaslawton Great catch! Would you be interested in submitting a PR for this? No worries if you don't though.

**Comment by nicholaslawton** [comment]
Made a quick change to add a few test cases to enforce correct behaviour for the flag combinations identified here.

I think it is probably complete, because it is only these three flags which determine which lines are selected. The other flags alter the output format. At a minimum, it should direct players towards a complete solution.

**Comment by ErikSchierboom** [comment]
@nicholaslawton Great work! I've just merged the PR. Thanks a lot for the help!
