### ISSUE TITLE
Add link to xfsharp gitter room

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/xfsharp#315]
I've just created a Gitter room for this repository at: https://gitter.im/exercism/xfsharp We should add this link to the documentation.

**Comment by tushartyagi** [comment]
@ErikSchierboom Added the PR [here](https://github.com/exercism/xfsharp/pull/317)

**Comment by ErikSchierboom** [comment]
@tushartyagi I think it would also make sense to add the link to the docs/resources.md file, which contents are displayed on exercism.io. Would you be willing to also send a pr for that?

**Comment by tushartyagi** [comment]
@ErikSchierboom created PR #318 for ^^

**Comment by ErikSchierboom** [comment]
Perfect.
