### ISSUE TITLE
triangle: incorrect test in some tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xfsharp#54]
Please check if there's a test that states that a triangle with sides 2, 4, 2 is invalid. The triangle inequality states that for any triangle, the sum of the lengths of any two sides must be greater than or equal to the length of the remaining side. If this doesn't affect this track, go ahead and just close the issue.

**Comment by ErikSchierboom** [comment]
There is such a test. See: https://github.com/exercism/xfsharp/blame/master/exercises/triangle/TriangleTest.fs#L76

**Comment by kytrinyx** [comment]
There shouldn't be such a test. 2, 4, 2 is valid.

**Comment by ErikSchierboom** [comment]
Whoops! I'll re-open the issue then.

**Comment by kytrinyx** [comment]
Thanks--there's some confusion here. Check out the discussion in the erlang track: https://github.com/exercism/xerlang/issues/85

**Comment by ErikSchierboom** [comment]
@kytrinyx I just read the Erlang discussion. Is the consensus there that the test should be modified or that it should be removed?

**Comment by kytrinyx** [comment]
I'm not sure yet. Let's give this a week, and then I'll summarize the discussion somewhere, make a recommendation, and then ask people to holler if they disagree.

**Comment by kytrinyx** [comment]
There was a bit of confusion with this issue. I've summarized my current understanding here: https://github.com/exercism/x-common/issues/202

I am closing this issue. If necessary I will open a new issue once we have come to an agreement about how to resolve the inconsistencies and what exact steps to take.
