### ISSUE TITLE
Implement AppVeyor build

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/xfsharp#56]
Having an AppVeyor build means we get to test the code on Windows. Now that our build script is almost finished, it seems like a no-brainer.

@jwood803 I have done this before, shall I assign myself to it?

**Comment by jwood803** [comment]
Sure! I haven't messed with AppVeyor in quite a while. If any help is needed, let me know.

**Comment by ErikSchierboom** [comment]
@jwood803 Well that was easy! PR #57 also adds AppVeyor support. :sunglasses:
