### ISSUE TITLE
Use idiomatic F#

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/xfsharp#59]
Many of the example implementations use classes to implement the desired functionality. However, I'm not sure this is idiomatic F#. Wouldn't just having some functions be more idiomatic? Especially when the class only has one method. In general, should our examples use object-oriented code or functional code? I think we should do the latter.

As an example, consider the `binary` exercise's example implementation:

```fsharp
module Binary

type Binary(input: string) =
    let rec toDecimalLoop acc input = 
        if input = "" then acc
        else 
            let head = input.Chars 0
            let tail = input.Substring 1
            match head with
                | '0' -> toDecimalLoop (acc * 2) tail
                | '1' -> toDecimalLoop (acc * 2 + 1) tail
                | _   -> 0   

    member this.toDecimal() = toDecimalLoop 0 input
```

Testing the functionality is done as follows:
```fsharp
Binary(input).toDecimal()
```

Wouldn't this be a more idiomatic, more functional F# implementation?

```fsharp
module Binary

let toDecimal (input: string) = toDecimalLoop 0 input

let private rec toDecimalLoop acc input = 
        if input = "" then acc
        else 
            let head = input.Chars 0
            let tail = input.Substring 1
            match head with
                | '0' -> toDecimalLoop (acc * 2) tail
                | '1' -> toDecimalLoop (acc * 2 + 1) tail
                | _   -> 0 
```

The test is also a bit more functional:

```fsharp
toDecimal input
```

What do you think?

**Comment by jwood803** [comment]
Honestly, when I first started adding exercises I was just learning F# so they will definitely be structured more like C#. I concur, though. It would be best to keep things more functional the way it's more intended to be used.

**Comment by ErikSchierboom** [comment]
@jwood803 Well, I also have a C# background and are still learning the joys of functional programming :) I will try to make the new exercises be more functional, and we'll see if that works out.

**Comment by jwood803** [comment]
Sounds good, @ErikSchierboom! Also, if you ever wish to pair on some of these, just let me know. I need to learn more of this stuff, as well. :p

**Comment by ErikSchierboom** [comment]
@jwood803 Great idea! How would you like to do that?

We can also "claim" exercises to prevent us doing double work. I've just assigned myself to the `kindergarten-garden` exercise in #60. Would that work for you?

**Comment by jwood803** [comment]
Maybe join.me or Screenhero? I can take a shot at `phone-number`, as well. Hope you don't expect it real soon, though. :}

**Comment by ErikSchierboom** [comment]
Sounds like a plan! Just send me an email (it's on [my profile](https://github.com/ErikSchierboom)) when you want to plan something.

I've added your initials to `phone-number`, I don't expect anything :)
