### ISSUE TITLE
Implement F# exercises 

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/xfsharp#60]
## Minimum Exercises to Implement

- [x] anagram
- [x] bob
- [x] etl
- [x] grade-school
- [x] hamming
- [x] leap
- [x] nucleotide-count
- [ ] phone-number (JW)
- [x] robot-name
- [x] word-count

## Additional Exercises to Implement

After the initial set of exercises the following should be implemented to have a more complete test suite.

- [x] accumulate
- [x] allergies
- [x] atbash-cipher
- [x] beer-song
- [x] binary
- [x] binary-search-tree
- [x] crypto-square
- [x] difference-of-squares
- [x] gigasecond
- [x] hexadecimal
- [x] kindergarten-garden
- [x] largest-series-product
- [x] linked-list
- [x] luhn
- [x] matrix
- [x] meetup
- [x] nth-prime
- [x] ocr-numbers
- [x] octal
- [x] palindrome-products
- [x] pascals-triangle
- [x] pig-latin
- [x] prime-factors
- [x] pythagorean-triplet
- [x] queen-attack
- [x] raindrops
- [x] rna-transcription
- [x] robot-simulator
- [x] roman-numerals
- [x] saddle-points
- [x] scrabble-score
- [x] secret-handshake
- [x] series
- [x] sieve
- [x] simple-cipher
- [x] simple-linked-list
- [x] space-age
- [x] strain
- [x] sum-of-multiples
- [x] triangle
- [x] trinary
- [x] twelve-days
- [x] wordy

**Comment by ErikSchierboom** [comment]
@jwood803 And this issue is almost done! The only exercise left open is the `phone-numbers` exercise, which you indicated you'd like to submit. Once that is done, we have a nice track of exercises :)

I'll move on to the issue #59, converting existing exercises to a more functional style.

**Comment by jwood803** [comment]
Awesome! Didn't realize you worked so quick :p

**Comment by ErikSchierboom** [comment]
I really liked this issue :) If you need any help, let me know.

**Comment by kytrinyx** [comment]
We have a new process that you can use to find exercises to implement.
You can read all about it [here](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track).

I'm closing this issue in favor of the process described in the Contributing guide linked to above.

Thanks!
